Initial commit
PalmDriveCapital/YC-scraper pull request #1
Opened 2021-07-28 16:35 UTC by kylehuang24

2021-07-28 16:57 UTC, DanMeyer requested changes
LGTM. Just a few small notes in comments.

2021-07-28 16:57 UTC, DanMeyer commented on scroller.py
> +        time.sleep(SCROLL_PAUSE_TIME)
Why a `sleep` versus some kind of "wait until the page has loaded"?

2021-07-28 16:57 UTC, DanMeyer commented on batch.py
> +def command_line():
I think you could do this where you have a tuple/list of all the batches:
```
batches = (
  ("S21", "Summer21"),
  ("W21", "Winter21"),
)
```

and then loop through those to do `parser.add_argument` and the `if args...`

2021-07-28 16:57 UTC, DanMeyer commented on batch.py
> +    if args.Winter21:
I _think_ you can say:
`if "Winter21" in args`

so you can do something like
```
for (full_name, short_name) in batches:
  if full_name in args:
   # probably should use f strings here
    s = s + "batch=" + short_name + "&"
```

2021-07-28 16:57 UTC, DanMeyer commented on scraper.py
> +    # scroller.scroll(driver)
Was commented-out for demo

2021-07-28 16:57 UTC, DanMeyer commented on scraper.py
> +        # Get information from new tab
Just for readability, I'd add a space here (and before all the other comment lines)

2021-07-28 16:57 UTC, DanMeyer commented on scraper.py
> +        # Get information from new tab
(Also, I dig that there are so many explanatory comments :)

2021-07-28 16:57 UTC, DanMeyer commented on scraper.py
> +
Extension idea:

I wonder if there's a way to save and restore the data frame if the scraper gets interrupted? Or maybe write to the files intermittently so progress is bookmarked? (But then you'd need a bunch more code to read/write the files, so maybe not worth it for now)

2021-07-28 16:57 UTC, DanMeyer commented on scraper.py
> +
As discussed verbally, I think this is too much work for the benefit right now. So you can just resolve this comment.

2021-07-29 18:01 UTC, kylehuang24 commented on batch.py
> +def command_line():
I played around with this. I'm just not sure you can add an argument with a variable name. It keeps saying it is an unrecognized argument when I pass the variable as the parameter in add_argument. Maybe it is a problem with variable assignment? Or maybe argparse doesn't allow you to pass variables as a parameter in add_argument?

https://docs.python.org/3/library/argparse.html#name-or-flags

2021-08-02 16:39 UTC, merged